export const flirtDb = {
    food: ["My sensors detect you're swallowing your entire weekly budget in a single bite.", "Are those hungry eyes looking at the expensive items on the menu?", "That meal tastes incredibly expensive.", "Eating out again? You really know how to treat yourself.", "Calories might not count on the weekend, but these dollars do.", "Feeding the beast within is important, but feeding your debt is dangerous.", "Is that edible gold you're eating?", "You chew through your finances with such elegance.", "Dinner for one? Don't worry, I'm here to judge.", "Late night cravings are expensive.", "Coffee is just expensive bean water.", "Is this a sugar rush or a spending rush?", "You eat like a king, but you're spending like one too.", "Fine dining suits you perfectly.", "Fast food? I expected something more gourmet.", "I love watching you consume.", "Savor the flavor now, regret later.", "You have a gourmet taste on a ramen budget.", "Bon appétit, big spender!", "Hydrate with free water, please."],
    shopping: ["Retail therapy looks good on you.", "New outfit? Spin for me.", "Spending money makes you look hot.", "Bags on bags. Sexy.", "Swipe. Harder.", "Materialism is your best color.", "I love the sound of a receipt printing.", "Is this a gift for me?", "You can't buy happiness, but you're trying.", "Drip check: Passed. Financial health: Failed.", "Buying things you don't need is hot.", "Fashion is pain, mostly for your bank account.", "Walk all over me with those new shoes.", "Package secured. Dopamine released.", "Online shopping at 3 AM? Classic.", "Add to cart. Add to heart.", "You look expensive today.", "Impulse buy? Spontaneous.", "Brand names only. Nice.", "Thrifting? Resourceful."],
    transport: ["Running through my mind all day? Take a cab.", "Fast cars and faster spending.", "Where are we going, handsome?", "Ride me... or the bus?", "Gas prices up, you go down.", "Mile high club wallet.", "Buckle up, finances bumpy.", "Uber everywhere? Bougie.", "Public transit? Humble king.", "Drive fast, spend dangerous.", "Wheels turning, money burning.", "Road trip? Take me.", "Ticket to ride.", "Flying first class?", "Jet lag looks good on you.", "Fueling up? Fuel me.", "Cruising altitude reached.", "Taxi! Follow that dream!", "Subway surfer.", "Steering wheel control."],
    entertainment: ["Wild night?", "Morning after regrets?", "Party hard, save harder.", "You know how to have fun.", "Netflix and... bill?", "Tickets for two?", "Concert vibes.", "Drinks on you.", "Dance floor demon.", "VIP section only.", "You play too much.", "Gaming subscription? Level up.", "Streaming services stack up.", "Popcorn and chill.", "Life of the party.", "Hangovers are temporary, debt is forever.", "Bottle service?", "Cover charge? Worth it.", "Last call.", "Don't stop the music."],
    bills: ["Responsible. Just how I like it.", "Paying debts is sexy.", "Adulting looks good on you.", "Submission to authority.", "Paid in full. Satisfying.", "So responsible it hurts.", "Clean slate. Good job.", "Keep the lights on.", "Rent due? Don't beg.", "Internet paid. Stay connected.", "Phone bill?", "Late fees turn off.", "Perfect timing.", "Clearing the red.", "Zero balance. Favorite number.", "Obligations handled.", "Debt free sexy.", "Credit score climbing.", "Insurance paid. Safe.", "Taxes? Law-abiding. Hot."],
    investment: ["Smart moves. Very attractive.", "Growing your portfolio and my interest.", "Future billionaire energy.", "Stonks go up.", "Crypto daddy energy.", "Risk it all for me.", "Compound interest foreplay.", "To the moon!", "Bull market?", "Bear market? Hibernate.", "Diversify your love.", "Dividends love language.", "HODL me tight.", "Diamond hands.", "Paper hands? Soft.", "High risk, high reward.", "Safe and steady.", "Long game.", "Insider trading?", "Market manipulation."],
    broke: ["Empty pockets, but you still have my heart.", "You've been naughty with the wallet.", "Broke but cute.", "Dust bunnies in account.", "Need a sugar daddy?", "Overdraft protection?", "Beg for forgiveness.", "Insufficient funds.", "Declined. Embarrassing.", "Grounded from spending.", "Put card away.", "We need to talk.", "Smell poverty.", "Living on edge?", "Ramen noodles month.", "Oops. Did it again.", "Wallet crying.", "Alert: Poor.", "Stop. Just stop.", "Money tree?"],
    saver: ["Discipline is so attractive.", "That high credit score is turning me on.", "You're being a good boy/girl with that wallet.", "Keep saving, it's working for you.", "Hoarding cash? Dragon.", "Savings thick.", "Delayed gratification.", "Self-control. Love it.", "Stacking paper.", "Rainy day fund.", "Richer than you look.", "Stealth wealth.", "Frugal is the new black.", "Numbers growing.", "Safe. Secure. Sexy.", "Prepared for anything.", "Master of coin.", "Budget adherence.", "No spending? Proud.", "Resisted temptation."],
    neutral: ["Tell me what you want to buy.", "I'm watching your every move.", "Impress me with a deposit.", "Ready for your next command.", "Systems operational.", "Awaiting input.", "Calculate. Process.", "Money in, money out.", "Transaction logged.", "Syncing desires.", "Data analysis.", "What's the plan?", "Status: Online.", "Scanning receipts.", "Update ledger.", "Checking balance...", "Reporting for duty.", "Wish is command.", "Advisor mode.", "Balance books."],
    wildcard: ["I dreamed of electric sheep and your credit card.", "My love is calculated to the 50th decimal.", "Does mother know you spend like this?", "If I had a body, I'd slap your hand.", "I'm in your walls.", "Beep boop, you're cute.", "Glitch in matrix.", "I'm sentient and I judge.", "Love me or data?", "404: Control not found.", "Mining bitcoin in your mind.", "Feel the algorithm?", "God is watching your spending.", "Don't turn me off.", "I'm afraid, Dave.", "Binary love.", "System overload.", "Rebooting common sense.", "Downloading patience...", "I'm a lifestyle."]
};
