export const hallIdentities = {
    "Sir Ashutosh Mukherjee Hall": { short: "SAM" },
    "Azad Hall of Residence": { short: "Azad" },
    "B C Roy Hall of Residence": { short: "BCR" },
    "B R Ambedkar Hall of Residence": { short: "BRA" },
    "Gokhale Hall of Residence": { short: "Gokhale" },
    "Visveswaraya Guest House": { short: "VGH" },
    "Homi J Bhabha Hall of Residence": { short: "HBH" },
    "Jagadish Chandra Bose Hall of Residence": { short: "JCB" },
    "Lal Bahadur Shastri Hall of Residence": { short: "LBS" },
    "Lala Lajpat Rai Hall of Residence": { short: "LLR" },
    "Madan Mohan Malviya Hall of Residence": { short: "MMM" },
    "Meghnad Saha Hall of Residence": { short: "MS" },
    "Mother Teresa Hall of Residence": { short: "MT" },
    "Nehru Hall of Residence": { short: "Nehru" },
    "Patel Hall of Residence": { short: "Patel" },
    "Radha Krishnan Hall of Residence": { short: "RK" },
    "Rani Laxmibai Hall of Residence": { short: "RLB" },
    "Rajendra Prasad Hall of Residence": { short: "RP" },
    "Sarojini Naidu - Indira Gandhi Hall of Residence": { short: "SN / IG" },
    "Sister Nivedita Hall of Residence": { short: "SN" },
    "Vidyasagar Hall of Residence": { short: "VS" },
    "Zakir Hussain Hall of Residence": { short: "ZH" },
    "Default": { short: "Hall" }
};
