export const rankTitles = {
    food: ["CEO of Swiggy", "Professional Eater", "Vending Machine MVP", "Caffeine Dependent", "Late Night Snacker", "Menu Memorizer", "Buffet Bandit", "Gourmet on Budget", "Calorie Collector", "Takeout King", "Snack Strategist", "Hungry Investor", "Lunch Break Legend", "Taco Tycoon", "Burger Baron", "Pizza Prophet"],
    shopping: ["Amazon's Best Friend", "Retail Therapist", "Cart Filler", "Impulse Buyer", "Brand Ambassador", "Delivery Addict", "Sale Hunter", "Window Shopper Pro", "Unboxing Expert", "Mall Rat", "Checkout Champion", "Receipt Collector", "Trend Setter", "Fashion Victim", "Online Spender", "Gadget Hoarder"],
    transport: ["Uber Platinum Member", "Globe Trotter", "Fuel Burner", "Mile High Club", "Road Warrior", "Commute King", "Taxi VIP", "Wanderlust Wallet", "Jet Setter", "Mileage Master", "Ticket Collector", "Asphalt Ace", "Highway Hero", "Navigator", "Destination Unknown", "Fare Payer"],
    entertainment: ["Weekend Warrior", "Vibe Curator", "Ticket Master", "Netflix Sponsor", "Party Animal", "Fun Fund Manager", "Cinema Buff", "Subscription Slave", "Concert Goer", "Night Owl", "Memory Maker", "Leisure Lord", "Hobby Hoarder", "Adrenaline Junkie", "Social Butterfly", "Event Planner"],
    bills: ["Utility Tycoon", "Adulting Pro", "Deadline Beater", "Interest Rate Slayer", "Credit Score Hero", "Responsible Citizen", "Bill Crusher", "Due Date Defender", "Fixed Cost Fanatic", "Rent Payer", "Subscription Manager", "Maintenance Man", "Overhead Officer", "Liability Leader", "Solvency Specialist", "Payment Prince"],
    investment: ["Wolf of Wall St", "Crypto Cowboy", "Future Millionaire", "Asset Accumulator", "Portfolio Prince", "Risk Taker", "Diamond Hands", "Compound Interest God", "Market Mover", "Dividend Dynasty", "Equity Expert", "Capital Captain", "Bull Run Believer", "Bear Market Boss", "Stonk Strategist", "Wealth Weaver"],
    education: ["Knowledge Investor", "Bookworm", "Tuition Titan", "Skill Seeker", "Library VIP", "Course Collector", "Wisdom Wallet", "Brainiac Spender", "Academic Ace", "Scholar Dollar", "Learning Legend", "Diploma Driver"],
    broke: ["Financial Daredevil", "Negative Balance King", "Debt Collector's Crush", "YOLO Economist", "Budget Breaker", "Overdraft Olympian", "Living on the Edge", "Red Alert", "Limit Pusher", "Fiscal Anarchist", "Credit Card Cowboy", "Broke Billionaire", "Spending Speeder", "Balance Zero Hero", "Insufficent Funds", "Wallet on Fire"],
    saver: ["Penny Pincher Supreme", "Dragon Sitting on Gold", "Savings Guru", "Coupon Hunter", "Frugal Master", "Budget Ninja", "Wealth Hoarder", "No Spend November", "Thrifty Titan", "Miserly Monarch", "Cash Keeper", "Interest Earner", "Safe Bet", "Rainy Day Ruler", "Stash Star", "Economy Class Hero"],
    balanced: ["Equilibrium Expert", "Middle Path Walker", "Zen Spender", "Stability Star", "Average Joe", "Predictable Patron", "Steady Eddie", "Balanced Beast", "Fiscal Moderate", "Center Lane Driver", "Normalcy Ninja", "Standard Setter"]
};
